name: pet_pet_app
description: 萌宠社交应用
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  dio: ^4.0.6
  image_picker: ^0.8.7+3
  qr_flutter: ^4.1.0
  fl_chart: ^0.55.2
  amap_flutter_map: ^3.0.0
  cached_network_image: ^3.2.3
  pull_to_refresh: ^2.0.0

dev_dependencies:
  flutter_lints: ^2.0.1
  build_runner: ^2.3.3 