server:
  port: 18888
  servlet:
    context-path: /mg
spring:
  application:
    name: api_market_mg
  datasource:
    url: "jdbc:mysql://127.0.0.1:3306/api_market"
    username: root
    password: P@ssW0rd1874
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
logging:
  level:
    org.springdoc.api: DEBUG
springdoc:
  default-produces-media-type: application/json
  api-docs:
    enabled: true
  swagger-ui:
    tags-sorter: alpha
    operations-sorter: alpha
    enabled: true

mail:
  smtp:
    host: smtp.163.com
    port: 465
    mail-from: aChen1874@163.com
    password: QZb5W3BjxEnfuvtF
auth:
  jwt:
    enable: true
    expire: 720000
cache:
  mode: caffeine